### ISSUE TITLE
Bug? Signed in without email verification

### ISSUE THREAD

**Issue by IndependentCreator** [delay/sveltekit-auth-starter#15]
Testing locally, I accidentally discovered a way to login without ever clicking on (or even receiving) the confirmation email:

1. Configure your .env with _incorrect_ SMTP login credentials
2. Start the dev server via `npm run dev`
3. Fill in the sign up fields in the browser and click "Sign Up"
4. Notice the server crashes. Console logs incorrectly report the email was sent successfully before subsequently failing with an SMTP authentication error, e.g.
```
E-mail sent successfully!
log:  {"level":"info","method":"GET","path":"/auth/verify/resend-email-a0455918-de53-4979-9aa4-3d72a06e491b","status":200,"timeInMs":1552,"user":"mrbogus@example.com","userId":"AhXN3CVU2QsGzOP","referer":"/auth/verify/email"}
log:  {"level":"info","method":"GET","path":"/","status":200,"timeInMs":4056,"user":"mrbogus@example.com","userId":"AhXN3CVU2QsGzOP","referer":"/auth/verify/email"}
E-mail sent successfully!
log:  {"level":"info","method":"GET","path":"/auth/verify/resend-email-a0455918-de53-4979-9aa4-3d72a06e491b","status":200,"timeInMs":654,"user":"mrbogus@example.com","userId":"AhXN3CVU2QsGzOP","referer":"/auth/verify/resend-email-a0455918-de53-4979-9aa4-3d72a06e491b"}
/src/lib/server/email-send.ts:78
            throw new Error(`Error sending email: ${JSON.stringify(err)}`);
            ^
Error: Error sending email: {"code":"EAUTH","response":"535 Incorrect authentication data","responseCode":535,"command":"AUTH PLAIN"}
    at eval (/src/lib/server/email-send.ts:78:19)
```
6. Restart the server with `npm run dev`
7. Return to the browser and click on the "If you did not receive the email, [click here] to resend it" link 
8. Notice the server crashes again with an SMTP Auth error
9. Restart the server with `npm run dev`
10. Return to the browser and visit http://localhost:5173/dashboard
11. Notice under Protected Area, it says "If you are seeing this page, you are logged in."
12. Visit http://localhost:5173/profile and notice that you can see your profile and make changes to it.

**Comment by delay** [comment]
If you misconfigure your setup, unknown problems can occur.  I would suggest making sure everything works, I don’t put extra checks to make sure you configured your system correctly. My recommendation is to setup AWS for production.

**Comment by IndependentCreator** [comment]
Thanks for the reply. Do you have any concerns that someone could use this behavior to create an exploit that would allow them to register without using a valid email address?

**Comment by delay** [comment]
If you configure your smtp settings with the correct info, can you replicate this trouble? It would concern me if correctly configuring allowed users to sign in.

**Comment by delay** [comment]
Also I don’t really understand how even if it fails to send how you can be verified.  When a user signs up, verified is set to false.  The only way to verify the user is you need to visit this page https://github.com/delay/sveltekit-auth-starter/blob/main/src/routes/auth/verify/email-%5Btoken%5D/%2Bpage.server.ts so that verified can be set to true.  Then you would see the protected page, without visiting that page with the correct token I am not sure how that would happen unless you changed verified to true on the sign up function.

**Comment by delay** [comment]
Oops you are right! thanks for sending this bug report… The problem is resend verification email incorrectly sets verified to true.  Thanks very much for reporting this!  I thought it was just a configuration issue but actually is a bad bug!

**Comment by delay** [comment]
It should be fixed now.  Thanks once again for reporting this trouble!  And sorry for not checking this out better after your first report.  Thanks so much for the follow up question, because it enabled me to think more about the problem and determine it shouldn't be happening whether the server was misconfigured or not.

**Comment by IndependentCreator** [comment]
No worries, I could have been more explicit in the initial report. Thanks for the quick fix and for putting together this example 🙂
