### ISSUE TITLE
Update Luica to v2

### ISSUE THREAD

**Issue by BradNut** [delay/sveltekit-auth-starter#18]
Update the starter to use v2 of Lucia: https://lucia-auth.com/start-here/migrate-v2

**Comment by delay** [comment]
I will try to get this updated.  I will also accept a PR for this if anyone wants to tackle it.

**Comment by deancochran** [comment]
Not sure I have time to make a PR. I never have contributed to Open Source code, but I'd like to! I did implement this stack with a Lucia upgrade. I ended up using Joy of Code's posts, HuntByte's posts, and many other resources including the docs!

Lmk how I can help, do you have a contributor page?

[My Repo](https://github.com/deancochran/skauth)

**Comment by delay** [comment]
Thanks for the offer!  If you want to make a pull request, clone my repository to your system.  Make the changes you want to.  Then submit the pull request to me. Here is one tutorial https://opensource.com/article/19/7/create-pull-request-github.   I am sure you can find many on how to submit a pull request if that one doesn't work.

I am going to update this repository to new versions of lucia-auth, skeleton, superforms and any other libraries that may be behind.  I haven't been coding much lately but plan to get back into things after Halloween.  If you want to give it a try before then I would be happy to take a look at what you submit and if it works well I will merge your pull request.  Otherwise I do plan to do this on my own in a couple of weeks.

**Comment by delay** [comment]
Also one other thing.  If you want to make other changes to the code besides just lucia-auth to version 2, please submit each as a different pull request that way I can accept each one individually and won't have to reject the whole request if there is some additional part of the update I don't want to perform.

**Comment by delay** [comment]
updated to version 2.  There are lot of changes including updates to the database schema.
